<Workspace Version="1.3.3.4111" X="160.458854302042" Y="312.164714262861" zoom="0.583576184043888" ScaleFactor="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Sphere" resolvedName="Autodesk.DesignScript.Geometry.Sphere" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="2b95664c-d00f-4427-b8d3-63348f337dc3" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.ByCoordinates" x="656.439691096689" y="-24.5708836121455" isVisible="true" isUpstreamVisible="true" lacing="CrossProduct" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="3fed147e-af72-435c-b9ac-a79af64cdb65" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="481.303892674053" y="16.5533225231615" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="0..100..#5;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="c9e4863b-39aa-4c8d-8057-026a047c13c1" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="852.960568947501" y="-21.2640589906213" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="sphereByZ(Pt);" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="c80645ab-dbcc-4aed-a113-266671dcacf4" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-73.5499089156439" y="16.7704278625081" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="def sphereByZ(inputPt)&#xA;{&#xA;	//get inputPt variables&#xA;	sphereRadius=(inputPt.Z)/20;&#xA;&#xA;	//define sphere&#xA;	sphere=Sphere.ByCenterPointRadius(inputPt,sphereRadius);&#xA;	//finally, define the function's output with 'return'&#xA;	return=sphere;&#xA;};" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="2b95664c-d00f-4427-b8d3-63348f337dc3" start_index="0" end="c9e4863b-39aa-4c8d-8057-026a047c13c1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3fed147e-af72-435c-b9ac-a79af64cdb65" start_index="0" end="2b95664c-d00f-4427-b8d3-63348f337dc3" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3fed147e-af72-435c-b9ac-a79af64cdb65" start_index="0" end="2b95664c-d00f-4427-b8d3-63348f337dc3" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3fed147e-af72-435c-b9ac-a79af64cdb65" start_index="0" end="2b95664c-d00f-4427-b8d3-63348f337dc3" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>